//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.18 at 07:30:35 PM MSK 
//


package com.vadim.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vadim.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Role_QNAME = new QName("", "Role");
    private final static QName _Lecture_QNAME = new QName("", "Lecture");
    private final static QName _User_QNAME = new QName("", "User");
    private final static QName _Course_QNAME = new QName("", "Course");
    private final static QName _UserLecture_QNAME = new QName("", "UserLecture");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vadim.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Lecture }
     * 
     */
    public Lecture createLecture() {
        return new Lecture();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link UserLecture }
     * 
     */
    public UserLecture createUserLecture() {
        return new UserLecture();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Role }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Role")
    public JAXBElement<Role> createRole(Role value) {
        return new JAXBElement<Role>(_Role_QNAME, Role.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Lecture }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Lecture")
    public JAXBElement<Lecture> createLecture(Lecture value) {
        return new JAXBElement<Lecture>(_Lecture_QNAME, Lecture.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "User")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Course }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Course")
    public JAXBElement<Course> createCourse(Course value) {
        return new JAXBElement<Course>(_Course_QNAME, Course.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserLecture }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserLecture")
    public JAXBElement<UserLecture> createUserLecture(UserLecture value) {
        return new JAXBElement<UserLecture>(_UserLecture_QNAME, UserLecture.class, null, value);
    }

}
